export const ARTICLES = [
  {
    id: 1,
    title:
      "Does Test Driven Development Really Improve Software Design Quality?",
    source: "IEEE, Software",
    publication: "2008",
    author: "Janzen, D.S.",
    volume: "25",
    number: 2,
    doi: "https://doi.org/10.1145/2601248.2601267",
    claim: "for",
    practice: "tdd",
  },
  {
    id: 2,
    title:
      "Realizing quality improvment through test driven development: results and experiences of four industrial teams",
    source: "IEEE, Software",
    publication: "2008",
    author: "Jenny, D.S.",
    volume: "25",
    number: 2,
    doi: "https://doi.org/10.1145/2601248.2601267",
    claim: "against",
    practice: "tdd",
  },
  {
    id: 3,
    title: "Does pair programming help in improving software quality?",
    source: "IEEE, Software",
    publication: "2008",
    author: "Janzen, D.S.",
    volume: "25",
    number: 2,
    doi: "https://doi.org/10.1145/2601248.2601267",
    claim: "for",
    practice: "mob programming",
  },
  {
    id: 4,
    title:
      "Does Test Driven Development Really Improve Software Design Quality?",
    source: "IEEE, Software",
    publication: "2001",
    author: "Jane, D.S.",
    volume: "25",
    number: 2,
    doi: "https://doi.org/10.1145/2601248.2601267",
    claim: "against",
    practice: "tdd",
  },
  {
    id: 5,
    title:
      "Does Mob programming slow down development time?",
    source: "IEEE, Software",
    publication: "2020",
    author: "John",
    volume: "25",
    number: 2,
    doi: "https://doi.org/10.1145/2601248.2601267",
    claim: "against",
    practice: "mob programming",
  },
];
