import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PopulatedNavBar from '@/components/PopulatedNavBar';
import 'bootstrap/dist/css/bootstrap.min.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SPEED',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PopulatedNavBar />
        {children}      
      </body>
    </html>
  )
}
