import './styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PopulatedNavBar from '@/components/PopulatedNavBar';
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SPEED',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="app">
        <div>
          <PopulatedNavBar />
          {children}      
        </div>
      </body>
    </html>
  )
}
