"use client";

import './styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PopulatedNavBar from '@/components/PopulatedNavBar';
import 'bootstrap/dist/css/bootstrap.min.css';
import './styles/globals.scss';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="app">
        <PopulatedNavBar />
        {children}      
      </body>
    </html>
  )
}